package ec.edu.ups.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-06-22T18:05:52.776-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://Services.ups.edu.ec/", name = "ClienteServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ClienteServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "deposito", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.Deposito")
    @ResponseWrapper(localName = "depositoResponse", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.DepositoResponse")
    public void deposito(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Double arg2
    );

    @WebMethod
    @RequestWrapper(localName = "retiro", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.Retiro")
    @ResponseWrapper(localName = "retiroResponse", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.RetiroResponse")
    public void retiro(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Double arg2
    );

    @WebMethod
    @RequestWrapper(localName = "transferencia", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.Transferencia")
    @ResponseWrapper(localName = "transferenciaResponse", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.TransferenciaResponse")
    public void transferencia(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Double arg2
    );
}
