package ec.edu.ups.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-07-08T18:09:33.664-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://Services.ups.edu.ec/", name = "ClienteServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ClienteServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "deposito", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.Deposito")
    @ResponseWrapper(localName = "depositoResponse", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.DepositoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.edu.ups.services.Respuesta deposito(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "retiro", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.Retiro")
    @ResponseWrapper(localName = "retiroResponse", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.RetiroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.edu.ups.services.Respuesta retiro(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Double arg2
    );

    @WebMethod
    @RequestWrapper(localName = "trans", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.Trans")
    @ResponseWrapper(localName = "transResponse", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.TransResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.edu.ups.services.Respuesta trans(
        @WebParam(name = "arg0", targetNamespace = "")
        ec.edu.ups.services.TransferenciaTemporal arg0
    );

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.edu.ups.services.Respuesta login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "buscarCliente", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.BuscarCliente")
    @ResponseWrapper(localName = "buscarClienteResponse", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.BuscarClienteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.edu.ups.services.ClienteTemporal buscarCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "listar", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://Services.ups.edu.ec/", className = "ec.edu.ups.services.ListarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.services.Cliente> listar();
}
