package ec.edu.ups.vista;

import java.awt.GridBagConstraints;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;
import javax.ws.rs.HttpMethod;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.xml.namespace.QName;

import org.glassfish.jersey.logging.LoggingFeature;

import ec.edu.ups.Modelo.ClienteTemporal;
import ec.edu.ups.Modelo.Respuesta;

/**
 *
 * @author Braulio Castro
 */
public class Deposito extends javax.swing.JInternalFrame {
	private ClienteTemporal cliente;

	/**
	 * Creates new form Depositos
	 */
	public Deposito() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabel4 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		btnAceptar = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		txtCorreo = new javax.swing.JTextField();
		txtCantidad = new javax.swing.JTextField();
		txtCuenta = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		txtCedula = new javax.swing.JTextField();
		btnConsultar = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		txtNombre = new javax.swing.JTextField();
		txtDepositante = new javax.swing.JTextField();

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("DEPÓSITOS");

		jPanel2.setBackground(new java.awt.Color(153, 153, 153));
		jPanel2.setLayout(new java.awt.GridBagLayout());

		btnAceptar.setText("Aceptar");
		btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnAceptar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAceptarActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		jPanel2.add(btnAceptar, gridBagConstraints);

		jPanel1.setBackground(new java.awt.Color(153, 153, 153));
		jPanel1.setForeground(new java.awt.Color(51, 51, 51));
		jPanel1.setLayout(new java.awt.GridBagLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(51, 51, 51));
		jLabel1.setText("RUC/C.I:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
		jPanel1.add(jLabel1, gridBagConstraints);

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(51, 51, 51));
		jLabel2.setText("Correo:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
		jPanel1.add(jLabel2, gridBagConstraints);

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(51, 51, 51));
		jLabel3.setText("Cantidad:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
		jPanel1.add(jLabel3, gridBagConstraints);

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(51, 51, 51));
		jLabel5.setText("Nombre:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		jPanel1.add(jLabel5, gridBagConstraints);

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(51, 51, 51));
		jLabel6.setText("Cuenta :");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		jPanel1.add(jLabel6, gridBagConstraints);

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(51, 51, 51));
		jLabel7.setText("Despositante :");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		jPanel1.add(jLabel7, gridBagConstraints);

		txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				txtNombreKeyTyped(evt);
			}
		});
		gbc_txtCorreo = new java.awt.GridBagConstraints();
		gbc_txtCorreo.gridx = 2;
		gbc_txtCorreo.gridy = 2;
		gbc_txtCorreo.fill = java.awt.GridBagConstraints.BOTH;
		gbc_txtCorreo.weightx = 0.5;
		jPanel1.add(txtCorreo, gbc_txtCorreo);

		txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				txtTelefonoKeyTyped(evt);
			}
		});
		gbc_txtCantidad = new java.awt.GridBagConstraints();
		gbc_txtCantidad.gridx = 2;
		gbc_txtCantidad.gridy = 4;
		gbc_txtCantidad.fill = java.awt.GridBagConstraints.BOTH;
		gbc_txtCantidad.weightx = 0.5;
		jPanel1.add(txtCantidad, gbc_txtCantidad);
		gbc_txtCuenta = new java.awt.GridBagConstraints();
		gbc_txtCuenta.gridx = 6;
		gbc_txtCuenta.gridy = 2;
		gbc_txtCuenta.fill = java.awt.GridBagConstraints.BOTH;
		gbc_txtCuenta.weightx = 0.5;
		gbc_txtCuenta.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(txtCuenta, gbc_txtCuenta);

		jPanel3.setLayout(new java.awt.GridBagLayout());

		txtCedula.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtDNIActionPerformed(evt);
			}
		});
		txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				txtDNIKeyTyped(evt);
			}
		});
		gbc_txtCedula = new java.awt.GridBagConstraints();
		gbc_txtCedula.gridx = 0;
		gbc_txtCedula.gridy = 0;
		gbc_txtCedula.fill = java.awt.GridBagConstraints.BOTH;
		gbc_txtCedula.weightx = 0.5;
		jPanel3.add(txtCedula, gbc_txtCedula);

		btnConsultar.setText("Buscar");
		btnConsultar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConsultarActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		jPanel3.add(btnConsultar, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		jPanel1.add(jPanel3, gridBagConstraints);

		jPanel4.setLayout(new java.awt.GridBagLayout());
		gbc_txtNombre = new java.awt.GridBagConstraints();
		gbc_txtNombre.gridx = 0;
		gbc_txtNombre.gridy = 0;
		gbc_txtNombre.fill = java.awt.GridBagConstraints.BOTH;
		gbc_txtNombre.weightx = 0.5;
		jPanel4.add(txtNombre, gbc_txtNombre);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jPanel4, gridBagConstraints);
		gbc_txtDepositante = new java.awt.GridBagConstraints();
		gbc_txtDepositante.gridx = 6;
		gbc_txtDepositante.gridy = 4;
		gbc_txtDepositante.fill = java.awt.GridBagConstraints.BOTH;
		gbc_txtDepositante.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(txtDepositante, gbc_txtDepositante);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE).addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup()
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(9, 9, 9)
										.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(101, 101, 101)));

		pack();
	}// </editor-fold>

	
	private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {
		
		Rest r = new Rest();
        Respuesta respuesta = r.desposito(cajero, cliente.getCedula(), Double.parseDouble(txtCantidad.getText()), txtDepositante.getText());
		JOptionPane.showMessageDialog(this, respuesta.getMensaje());
		txtCantidad.setText("");
		txtCedula.setText("");
		txtNombre.setText("");
		txtCorreo.setText("");
		txtCuenta.setText("");
		txtDepositante.setText("");
	}

	private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {
		char c = evt.getKeyChar();

		if (!(Character.isLetter(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_SPACE)) {
			getToolkit().beep();
			evt.consume();

			JOptionPane.showMessageDialog(this, "ERROR..! Por favor, ingrese solo letras");
		} // Fin if
	}

	private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {
		char c = evt.getKeyChar();

		if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE)) {
			getToolkit().beep();
			evt.consume();
			JOptionPane.showMessageDialog(this, "ERROR..! Por favor, ingrese solo números");
		} // Fin if
	}

	private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {
		btnConsultarActionPerformed(null);
	}

	private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {
		char c = evt.getKeyChar();

		if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == evt.VK_ENTER)) {
			getToolkit().beep();
			evt.consume();
			JOptionPane.showMessageDialog(this, "ERROR..! Por favor, ingrese solo números");
		} // Fin if
	}

	private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {
		Rest r = new Rest();
		try {
			
	        ClienteTemporal ct = r.buscarCliente(txtCedula.getText());
			if (ct == null) {
				JOptionPane.showMessageDialog(this, "El Cliente No EXISTE");
			} else {
				cliente = ct;
				txtCorreo.setText(cliente.getCorreo());
				txtNombre.setText(cliente.getNombre());
				txtCuenta.setText(cliente.getCuenta());
			}
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println("Expected exception: Exception has occurred.");
			System.out.println(e.toString());
		}
		{

		}
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnAceptar;
	private javax.swing.JButton btnConsultar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTextField txtDepositante;
	public static javax.swing.JTextField txtNombre;
	public static javax.swing.JTextField txtCedula;
	public static javax.swing.JTextField txtCuenta;
	public static javax.swing.JTextField txtCorreo;
	public static javax.swing.JTextField txtCantidad;
	public static String cajero;
	private GridBagConstraints gbc_txtCedula;
	private GridBagConstraints gbc_txtCorreo;
	private GridBagConstraints gbc_txtCantidad;
	private GridBagConstraints gbc_txtNombre;
	private GridBagConstraints gbc_txtCuenta;
	private GridBagConstraints gbc_txtDepositante;
	// End of variables declaration
}
