
package ec.edu.ups.appdis;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-06-29T15:34:43.026-05:00
 * Generated source version: 2.7.2
 */

@WebFault(name = "Exception", targetNamespace = "http://Services.ups.edu.ec/")
public class Exception_Exception extends java.lang.Exception {
    
    private ec.edu.ups.appdis.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, ec.edu.ups.appdis.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, ec.edu.ups.appdis.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public ec.edu.ups.appdis.Exception getFaultInfo() {
        return this.exception;
    }
}
